// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Create(category *models.Category) error {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Category) error); ok {
		r0 = returnFunc(category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - category *models.Category
func (_e *MockCategoryRepository_Expecter) Create(category interface{}) *MockCategoryRepository_Create_Call {
	return &MockCategoryRepository_Create_Call{Call: _e.mock.On("Create", category)}
}

func (_c *MockCategoryRepository_Create_Call) Run(run func(category *models.Category)) *MockCategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Category
		if args[0] != nil {
			arg0 = args[0].(*models.Category)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_Create_Call) Return(err error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_Create_Call) RunAndReturn(run func(category *models.Category) error) *MockCategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Delete(ID uint) error {
	ret := _mock.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ID uint
func (_e *MockCategoryRepository_Expecter) Delete(ID interface{}) *MockCategoryRepository_Delete_Call {
	return &MockCategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ID)}
}

func (_c *MockCategoryRepository_Delete_Call) Run(run func(ID uint)) *MockCategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) Return(err error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_Delete_Call) RunAndReturn(run func(ID uint) error) *MockCategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) GetAllByUserID(userID uint) ([]models.Category, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]models.Category, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []models.Category); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockCategoryRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *MockCategoryRepository_Expecter) GetAllByUserID(userID interface{}) *MockCategoryRepository_GetAllByUserID_Call {
	return &MockCategoryRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockCategoryRepository_GetAllByUserID_Call) Run(run func(userID uint)) *MockCategoryRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_GetAllByUserID_Call) Return(categorys []models.Category, err error) *MockCategoryRepository_GetAllByUserID_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryRepository_GetAllByUserID_Call) RunAndReturn(run func(userID uint) ([]models.Category, error)) *MockCategoryRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUserId provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) GetByIDAndUserId(ID uint, userId uint) (*models.Category, error) {
	ret := _mock.Called(ID, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUserId")
	}

	var r0 *models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*models.Category, error)); ok {
		return returnFunc(ID, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *models.Category); ok {
		r0 = returnFunc(ID, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(ID, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_GetByIDAndUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUserId'
type MockCategoryRepository_GetByIDAndUserId_Call struct {
	*mock.Call
}

// GetByIDAndUserId is a helper method to define mock.On call
//   - ID uint
//   - userId uint
func (_e *MockCategoryRepository_Expecter) GetByIDAndUserId(ID interface{}, userId interface{}) *MockCategoryRepository_GetByIDAndUserId_Call {
	return &MockCategoryRepository_GetByIDAndUserId_Call{Call: _e.mock.On("GetByIDAndUserId", ID, userId)}
}

func (_c *MockCategoryRepository_GetByIDAndUserId_Call) Run(run func(ID uint, userId uint)) *MockCategoryRepository_GetByIDAndUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_GetByIDAndUserId_Call) Return(category *models.Category, err error) *MockCategoryRepository_GetByIDAndUserId_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryRepository_GetByIDAndUserId_Call) RunAndReturn(run func(ID uint, userId uint) (*models.Category, error)) *MockCategoryRepository_GetByIDAndUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) Update(category *models.Category) error {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Category) error); ok {
		r0 = returnFunc(category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - category *models.Category
func (_e *MockCategoryRepository_Expecter) Update(category interface{}) *MockCategoryRepository_Update_Call {
	return &MockCategoryRepository_Update_Call{Call: _e.mock.On("Update", category)}
}

func (_c *MockCategoryRepository_Update_Call) Run(run func(category *models.Category)) *MockCategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Category
		if args[0] != nil {
			arg0 = args[0].(*models.Category)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_Update_Call) Return(err error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_Update_Call) RunAndReturn(run func(category *models.Category) error) *MockCategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
