// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExpenseRepository creates a new instance of MockExpenseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExpenseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExpenseRepository {
	mock := &MockExpenseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExpenseRepository is an autogenerated mock type for the ExpenseRepository type
type MockExpenseRepository struct {
	mock.Mock
}

type MockExpenseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExpenseRepository) EXPECT() *MockExpenseRepository_Expecter {
	return &MockExpenseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) Create(expense *models.Expense) error {
	ret := _mock.Called(expense)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Expense) error); ok {
		r0 = returnFunc(expense)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockExpenseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - expense *models.Expense
func (_e *MockExpenseRepository_Expecter) Create(expense interface{}) *MockExpenseRepository_Create_Call {
	return &MockExpenseRepository_Create_Call{Call: _e.mock.On("Create", expense)}
}

func (_c *MockExpenseRepository_Create_Call) Run(run func(expense *models.Expense)) *MockExpenseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Expense
		if args[0] != nil {
			arg0 = args[0].(*models.Expense)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_Create_Call) Return(err error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_Create_Call) RunAndReturn(run func(expense *models.Expense) error) *MockExpenseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) Delete(ID uint) error {
	ret := _mock.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExpenseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ID uint
func (_e *MockExpenseRepository_Expecter) Delete(ID interface{}) *MockExpenseRepository_Delete_Call {
	return &MockExpenseRepository_Delete_Call{Call: _e.mock.On("Delete", ID)}
}

func (_c *MockExpenseRepository_Delete_Call) Run(run func(ID uint)) *MockExpenseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) Return(err error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_Delete_Call) RunAndReturn(run func(ID uint) error) *MockExpenseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) GetAllByUserID(userID uint) ([]models.Expense, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Expense
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]models.Expense, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []models.Expense); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Expense)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockExpenseRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *MockExpenseRepository_Expecter) GetAllByUserID(userID interface{}) *MockExpenseRepository_GetAllByUserID_Call {
	return &MockExpenseRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockExpenseRepository_GetAllByUserID_Call) Run(run func(userID uint)) *MockExpenseRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_GetAllByUserID_Call) Return(expenses []models.Expense, err error) *MockExpenseRepository_GetAllByUserID_Call {
	_c.Call.Return(expenses, err)
	return _c
}

func (_c *MockExpenseRepository_GetAllByUserID_Call) RunAndReturn(run func(userID uint) ([]models.Expense, error)) *MockExpenseRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdAndUserId provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) GetByIdAndUserId(ID uint, userID uint) (*models.Expense, error) {
	ret := _mock.Called(ID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdAndUserId")
	}

	var r0 *models.Expense
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*models.Expense, error)); ok {
		return returnFunc(ID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *models.Expense); ok {
		r0 = returnFunc(ID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Expense)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(ID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExpenseRepository_GetByIdAndUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdAndUserId'
type MockExpenseRepository_GetByIdAndUserId_Call struct {
	*mock.Call
}

// GetByIdAndUserId is a helper method to define mock.On call
//   - ID uint
//   - userID uint
func (_e *MockExpenseRepository_Expecter) GetByIdAndUserId(ID interface{}, userID interface{}) *MockExpenseRepository_GetByIdAndUserId_Call {
	return &MockExpenseRepository_GetByIdAndUserId_Call{Call: _e.mock.On("GetByIdAndUserId", ID, userID)}
}

func (_c *MockExpenseRepository_GetByIdAndUserId_Call) Run(run func(ID uint, userID uint)) *MockExpenseRepository_GetByIdAndUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_GetByIdAndUserId_Call) Return(expense *models.Expense, err error) *MockExpenseRepository_GetByIdAndUserId_Call {
	_c.Call.Return(expense, err)
	return _c
}

func (_c *MockExpenseRepository_GetByIdAndUserId_Call) RunAndReturn(run func(ID uint, userID uint) (*models.Expense, error)) *MockExpenseRepository_GetByIdAndUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockExpenseRepository
func (_mock *MockExpenseRepository) Update(expense *models.Expense) error {
	ret := _mock.Called(expense)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Expense) error); ok {
		r0 = returnFunc(expense)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExpenseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExpenseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - expense *models.Expense
func (_e *MockExpenseRepository_Expecter) Update(expense interface{}) *MockExpenseRepository_Update_Call {
	return &MockExpenseRepository_Update_Call{Call: _e.mock.On("Update", expense)}
}

func (_c *MockExpenseRepository_Update_Call) Run(run func(expense *models.Expense)) *MockExpenseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Expense
		if args[0] != nil {
			arg0 = args[0].(*models.Expense)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExpenseRepository_Update_Call) Return(err error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExpenseRepository_Update_Call) RunAndReturn(run func(expense *models.Expense) error) *MockExpenseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
