// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"backend/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Create(subscription *models.Subscription) error {
	ret := _mock.Called(subscription)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Subscription) error); ok {
		r0 = returnFunc(subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - subscription *models.Subscription
func (_e *MockSubscriptionRepository_Expecter) Create(subscription interface{}) *MockSubscriptionRepository_Create_Call {
	return &MockSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", subscription)}
}

func (_c *MockSubscriptionRepository_Create_Call) Run(run func(subscription *models.Subscription)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Subscription
		if args[0] != nil {
			arg0 = args[0].(*models.Subscription)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) Return(err error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) RunAndReturn(run func(subscription *models.Subscription) error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Delete(ID uint) error {
	ret := _mock.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ID uint
func (_e *MockSubscriptionRepository_Expecter) Delete(ID interface{}) *MockSubscriptionRepository_Delete_Call {
	return &MockSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ID)}
}

func (_c *MockSubscriptionRepository_Delete_Call) Run(run func(ID uint)) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) Return(err error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Delete_Call) RunAndReturn(run func(ID uint) error) *MockSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByUserID provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) GetAllByUserID(userID uint) ([]models.Subscription, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) ([]models.Subscription, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) []models.Subscription); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_GetAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUserID'
type MockSubscriptionRepository_GetAllByUserID_Call struct {
	*mock.Call
}

// GetAllByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *MockSubscriptionRepository_Expecter) GetAllByUserID(userID interface{}) *MockSubscriptionRepository_GetAllByUserID_Call {
	return &MockSubscriptionRepository_GetAllByUserID_Call{Call: _e.mock.On("GetAllByUserID", userID)}
}

func (_c *MockSubscriptionRepository_GetAllByUserID_Call) Run(run func(userID uint)) *MockSubscriptionRepository_GetAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetAllByUserID_Call) Return(subscriptions []models.Subscription, err error) *MockSubscriptionRepository_GetAllByUserID_Call {
	_c.Call.Return(subscriptions, err)
	return _c
}

func (_c *MockSubscriptionRepository_GetAllByUserID_Call) RunAndReturn(run func(userID uint) ([]models.Subscription, error)) *MockSubscriptionRepository_GetAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDAndUserId provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) GetByIDAndUserId(ID uint, userID uint) (*models.Subscription, error) {
	ret := _mock.Called(ID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDAndUserId")
	}

	var r0 *models.Subscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*models.Subscription, error)); ok {
		return returnFunc(ID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *models.Subscription); ok {
		r0 = returnFunc(ID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(ID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSubscriptionRepository_GetByIDAndUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDAndUserId'
type MockSubscriptionRepository_GetByIDAndUserId_Call struct {
	*mock.Call
}

// GetByIDAndUserId is a helper method to define mock.On call
//   - ID uint
//   - userID uint
func (_e *MockSubscriptionRepository_Expecter) GetByIDAndUserId(ID interface{}, userID interface{}) *MockSubscriptionRepository_GetByIDAndUserId_Call {
	return &MockSubscriptionRepository_GetByIDAndUserId_Call{Call: _e.mock.On("GetByIDAndUserId", ID, userID)}
}

func (_c *MockSubscriptionRepository_GetByIDAndUserId_Call) Run(run func(ID uint, userID uint)) *MockSubscriptionRepository_GetByIDAndUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByIDAndUserId_Call) Return(subscription *models.Subscription, err error) *MockSubscriptionRepository_GetByIDAndUserId_Call {
	_c.Call.Return(subscription, err)
	return _c
}

func (_c *MockSubscriptionRepository_GetByIDAndUserId_Call) RunAndReturn(run func(ID uint, userID uint) (*models.Subscription, error)) *MockSubscriptionRepository_GetByIDAndUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockSubscriptionRepository
func (_mock *MockSubscriptionRepository) Update(ID uint, subscription *models.Subscription) error {
	ret := _mock.Called(ID, subscription)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint, *models.Subscription) error); ok {
		r0 = returnFunc(ID, subscription)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubscriptionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSubscriptionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ID uint
//   - subscription *models.Subscription
func (_e *MockSubscriptionRepository_Expecter) Update(ID interface{}, subscription interface{}) *MockSubscriptionRepository_Update_Call {
	return &MockSubscriptionRepository_Update_Call{Call: _e.mock.On("Update", ID, subscription)}
}

func (_c *MockSubscriptionRepository_Update_Call) Run(run func(ID uint, subscription *models.Subscription)) *MockSubscriptionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 *models.Subscription
		if args[1] != nil {
			arg1 = args[1].(*models.Subscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) Return(err error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubscriptionRepository_Update_Call) RunAndReturn(run func(ID uint, subscription *models.Subscription) error) *MockSubscriptionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
